apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: http
  name: http
spec:
  type: NodePort
  ports:
    # - name: "93"
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    io.kompose.service: http
