apiVersion: v1
data:
  default: "server {\n    listen 80 default_server;\n    listen [::]:80 default_server;\n    \n    root /usr/share/nginx/html;\n    index index.html index.htm;\n\n    server_name _;\n    location / {\n        try_files $uri $uri/ =404;\n    }\n}"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: http
  name: http-cm0
