apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: http
  name: http
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: http
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/app-test-net: "true"
        io.kompose.service: http
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_HOST
              value: sql
            - name: MYSQL_PASSWORD
              value: password_123!
            - name: MYSQL_USER
              value: root
          image: localhost:5000/http
          name: http
          # ports:
          #   - containerPort: 80
          #     hostPort: 93
          #     protocol: TCP
          volumeMounts:
            - mountPath: /etc/php/sites-available/default
              name: http-cm0
              subPath: default
            - mountPath: /var/www/html
              name: html-files
           
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: default
                path: default
            name: http-cm0
          name: http-cm0
        - configMap:
            name: http-cm1
          name: http-cm1
        - name: html-files
          hostPath:
            # path: /home/daniel/ZT_RKE2/app/http/frontend/src
            path: /home/dc/ZT_RKE2/app/http/frontend/src
            type: Directory
