apiVersion: v1
data:
  db_init.sql: "CREATE TABLE abc( \n    LetterID varchar(100) NOT NULL PRIMARY KEY,\n    NumberID int\n);\n\nINSERT INTO abc(LetterID, NumberID) \nVALUES (\"a\",1), (\"b\",2), (\"c\",3);\n\nCREATE TABLE users (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    username VARCHAR(50) NOT NULL,\n    password VARCHAR(255) NOT NULL\n);\n\n"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: sql
  name: sql-cm1
