apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /usr/local/volumes
  persistentVolumeReclaimPolicy: Retain
