apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # labels:
  #   io.kompose.service: sql-vol
  name: sql-vol
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 750Mi
