apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: sql
  name: sql
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 33060
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: sql
