apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: ssh
  name: ssh
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 22
  selector:
    io.kompose.service: ssh
