services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    #  - PUBLIC_KEY=yourpublickey #optional
    #  - PUBLIC_KEY_FILE=/path/to/file #optional
    #  - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
    #  - PUBLIC_KEY_URL=https://github.com/username.keys #optional
    #  - SUDO_ACCESS=false optional
    #   - PASSWORD_ACCESS=false #optional
    #   - USER_PASSWORD=password #optional
    #   - USER_PASSWORD_FILE=/path/to/file #optional
    #   - USER_NAME=linuxserver.io #optional
    #   - LOG_STDOUT= #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped
  basic_html: 
    image: nginx
    ports: 
      - 8080:80
    environment: 
      - NGINX_PORT=80
      - NGINX_HOST=test.com
  sql_db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - 1433:1433 
    environment: 
      - ACCEPT_EULA=Y
      - "MSSQL_SA_PASSWORD=pas!@0jeaf0sdfji2~"


